// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {IAgentRegistry} from "./interfaces/IAgentRegistry.sol";

/// @title IZKCreditVerifier - Interface for the ZK Credit Verifier
interface IZKCreditVerifier {
    struct ProofData {
        bytes proof;
        uint64 revenueThreshold;
        bytes32 registeredCodeHash;
        uint64 minReputation;
        uint256 agentId;
        uint8 revenueTier;
        uint8 reputationBand;
    }

    event ProofVerified(
        uint256 indexed agentId,
        uint64 revenueThreshold,
        uint64 minReputation,
        uint8 revenueTier,
        uint8 reputationBand,
        uint256 timestamp
    );
    event ProofRejected(uint256 indexed agentId, string reason);
    event VerifierKeyUpdated(bytes32 oldKeyHash, bytes32 newKeyHash);

    function verifyCredit(ProofData calldata proofData) external returns (bool);
    function isProofValid(uint256 agentId) external view returns (bool);
    function getVerificationTimestamp(uint256 agentId) external view returns (uint256);
}

/// @title ZKCreditVerifier - On-chain ZK proof verifier for Lenclaw credit scoring
/// @notice Verifies UltraPlonk proofs generated by the Noir circuit to attest
///         agent creditworthiness without revealing private data.
/// @dev Integrates with CreditScorer and AgentRegistry. The verifier key is
///      generated via `nargo codegen-verifier` from the compiled circuit.
///
/// Proof lifecycle:
///   1. Agent runs prover off-chain with private data
///   2. Proof + public inputs submitted to this contract
///   3. Contract verifies proof using the UltraPlonk verification algorithm
///   4. If valid, stores verification result for CreditScorer to query
contract ZKCreditVerifier is Ownable, IZKCreditVerifier {
    // =========================================================================
    // State
    // =========================================================================

    /// @notice The AgentRegistry contract for validating agent identity
    IAgentRegistry public immutable agentRegistry;

    /// @notice Hash of the current verifier key (updated when circuit changes)
    bytes32 public verifierKeyHash;

    /// @notice Mapping from agentId => whether they have a valid proof on file
    mapping(uint256 => bool) private _proofValid;

    /// @notice Mapping from agentId => timestamp of last successful verification
    mapping(uint256 => uint256) private _verificationTimestamp;

    /// @notice Mapping from agentId => the proof data for the last verification
    mapping(uint256 => ProofData) private _lastProof;

    /// @notice How long a proof remains valid before requiring re-verification
    uint256 public proofValidityPeriod = 7 days;

    /// @notice Minimum revenue threshold that must be proven
    uint64 public globalRevenueThreshold;

    /// @notice Minimum reputation score that must be proven
    uint64 public globalMinReputation = 300;

    // =========================================================================
    // UltraPlonk Verification Constants
    // =========================================================================

    /// @dev BN254 curve order
    uint256 internal constant BN254_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @dev Number of public inputs for our circuit:
    ///      [revenue_threshold, registered_code_hash, min_reputation, agent_id, revenue_tier, reputation_band]
    uint256 internal constant NUM_PUBLIC_INPUTS = 6;

    // =========================================================================
    // Constructor
    // =========================================================================

    /// @param _agentRegistry Address of the AgentRegistry contract
    /// @param _owner Admin address
    /// @param _verifierKeyHash Hash of the initial verifier key
    constructor(
        address _agentRegistry,
        address _owner,
        bytes32 _verifierKeyHash
    ) Ownable(_owner) {
        require(_agentRegistry != address(0), "ZKCreditVerifier: zero registry");
        agentRegistry = IAgentRegistry(_agentRegistry);
        verifierKeyHash = _verifierKeyHash;
    }

    // =========================================================================
    // Admin Functions
    // =========================================================================

    /// @notice Update the verifier key hash when the circuit is recompiled
    /// @param _newKeyHash Hash of the new verifier key
    function updateVerifierKey(bytes32 _newKeyHash) external onlyOwner {
        bytes32 oldHash = verifierKeyHash;
        verifierKeyHash = _newKeyHash;
        emit VerifierKeyUpdated(oldHash, _newKeyHash);
    }

    /// @notice Set the proof validity period
    /// @param _period Duration in seconds
    function setProofValidityPeriod(uint256 _period) external onlyOwner {
        require(_period >= 1 hours, "ZKCreditVerifier: period too short");
        require(_period <= 30 days, "ZKCreditVerifier: period too long");
        proofValidityPeriod = _period;
    }

    /// @notice Set global minimum thresholds for credit eligibility
    /// @param _revenueThreshold Minimum revenue in USDC (6 decimals)
    /// @param _minReputation Minimum reputation score (0-1000)
    function setGlobalThresholds(uint64 _revenueThreshold, uint64 _minReputation) external onlyOwner {
        require(_minReputation <= 1000, "ZKCreditVerifier: reputation out of range");
        globalRevenueThreshold = _revenueThreshold;
        globalMinReputation = _minReputation;
    }

    // =========================================================================
    // Core Verification
    // =========================================================================

    /// @notice Verify a ZK credit proof for an agent
    /// @param proofData The proof and its public inputs
    /// @return valid True if the proof is valid
    function verifyCredit(ProofData calldata proofData) external returns (bool valid) {
        // 1. Validate the agent exists in the registry
        require(agentRegistry.isRegistered(proofData.agentId), "ZKCreditVerifier: agent not registered");

        // 2. Validate public input thresholds meet global minimums
        require(
            proofData.revenueThreshold >= globalRevenueThreshold,
            "ZKCreditVerifier: revenue threshold below global minimum"
        );
        require(
            proofData.minReputation >= globalMinReputation,
            "ZKCreditVerifier: reputation below global minimum"
        );

        // 3. Validate the code hash matches what's registered on-chain
        IAgentRegistry.AgentProfile memory profile = agentRegistry.getAgent(proofData.agentId);
        require(
            proofData.registeredCodeHash == profile.codeHash,
            "ZKCreditVerifier: code hash mismatch with registry"
        );

        // 4. Validate revenue tier and reputation band are in valid ranges
        require(proofData.revenueTier <= 4, "ZKCreditVerifier: invalid revenue tier");
        require(proofData.reputationBand <= 3, "ZKCreditVerifier: invalid reputation band");

        // 5. Verify the ZK proof
        valid = _verifyUltraPlonkProof(
            proofData.proof,
            proofData.revenueThreshold,
            proofData.registeredCodeHash,
            proofData.minReputation,
            proofData.agentId,
            proofData.revenueTier,
            proofData.reputationBand
        );

        if (valid) {
            // Store verification result
            _proofValid[proofData.agentId] = true;
            _verificationTimestamp[proofData.agentId] = block.timestamp;
            _lastProof[proofData.agentId] = proofData;

            emit ProofVerified(
                proofData.agentId,
                proofData.revenueThreshold,
                proofData.minReputation,
                proofData.revenueTier,
                proofData.reputationBand,
                block.timestamp
            );
        } else {
            emit ProofRejected(proofData.agentId, "Invalid proof");
        }
    }

    /// @notice Check if an agent has a currently valid proof
    /// @param agentId The agent's NFT ID
    /// @return True if the agent has a valid, non-expired proof
    function isProofValid(uint256 agentId) external view returns (bool) {
        if (!_proofValid[agentId]) return false;
        // Check if the proof has expired
        return (block.timestamp - _verificationTimestamp[agentId]) <= proofValidityPeriod;
    }

    /// @notice Get the timestamp of the last successful verification
    /// @param agentId The agent's NFT ID
    /// @return Timestamp, or 0 if never verified
    function getVerificationTimestamp(uint256 agentId) external view returns (uint256) {
        return _verificationTimestamp[agentId];
    }

    /// @notice Get the last verified proof data for an agent
    /// @param agentId The agent's NFT ID
    /// @return The stored proof data
    function getLastProof(uint256 agentId) external view returns (ProofData memory) {
        require(_proofValid[agentId], "ZKCreditVerifier: no valid proof");
        return _lastProof[agentId];
    }

    /// @notice Get the revenue tier from the last verified proof
    /// @param agentId The agent's NFT ID
    /// @return Revenue tier (0-4)
    function getRevenueTier(uint256 agentId) external view returns (uint8) {
        require(_proofValid[agentId], "ZKCreditVerifier: no valid proof");
        return _lastProof[agentId].revenueTier;
    }

    /// @notice Get the reputation band from the last verified proof
    /// @param agentId The agent's NFT ID
    /// @return Reputation band (0-3)
    function getReputationBand(uint256 agentId) external view returns (uint8) {
        require(_proofValid[agentId], "ZKCreditVerifier: no valid proof");
        return _lastProof[agentId].reputationBand;
    }

    /// @notice Invalidate a proof (e.g., if agent is flagged)
    /// @param agentId The agent's NFT ID
    function invalidateProof(uint256 agentId) external onlyOwner {
        _proofValid[agentId] = false;
        delete _verificationTimestamp[agentId];
    }

    // =========================================================================
    // Internal: UltraPlonk Verification
    // =========================================================================

    /// @dev Verify an UltraPlonk proof against the stored verification key.
    ///
    /// In production, this function would contain the full UltraPlonk verification
    /// algorithm generated by `nargo codegen-verifier`. The generated verifier
    /// performs elliptic curve pairing checks on BN254.
    ///
    /// The verification algorithm:
    ///   1. Decode the proof into elliptic curve points and field elements
    ///   2. Reconstruct the public input polynomial from the public inputs
    ///   3. Perform the pairing check: e(A, B) == e(C, D)
    ///   4. Return true if the pairing equation holds
    ///
    /// For the MVP, we implement the interface with structural validation.
    /// Replace with generated verifier code after running:
    ///   cd zk/circuits && nargo codegen-verifier
    function _verifyUltraPlonkProof(
        bytes calldata proof,
        uint64 revenueThreshold,
        bytes32 registeredCodeHash,
        uint64 minReputation,
        uint256 agentId,
        uint8 revenueTier,
        uint8 reputationBand
    ) internal view returns (bool) {
        // Validate proof structure
        // UltraPlonk proofs consist of group elements and field elements.
        // Minimum proof size: 7 group elements (2 * 32 bytes each) + 5 field elements (32 bytes each)
        // = 7 * 64 + 5 * 32 = 448 + 160 = 608 bytes minimum
        if (proof.length < 608) {
            return false;
        }

        // Validate proof is properly structured (length is multiple of 32)
        if (proof.length % 32 != 0) {
            return false;
        }

        // Validate public inputs are within BN254 scalar field
        if (uint256(revenueThreshold) >= BN254_SCALAR_FIELD) return false;
        if (uint256(registeredCodeHash) >= BN254_SCALAR_FIELD) return false;
        if (uint256(minReputation) >= BN254_SCALAR_FIELD) return false;
        if (agentId >= BN254_SCALAR_FIELD) return false;

        // =====================================================================
        // PLACEHOLDER: Replace this block with the generated UltraPlonk verifier
        // from `nargo codegen-verifier`.
        //
        // The generated code will contain:
        //   - Verification key points (G1, G2 elements)
        //   - Transcript reconstruction (Fiat-Shamir)
        //   - Commitment opening checks
        //   - Pairing check via precompiles (ecAdd, ecMul, ecPairing)
        //
        // To generate:
        //   1. cd zk/circuits
        //   2. nargo compile
        //   3. nargo codegen-verifier
        //   4. Copy the verify() function body here
        // =====================================================================

        // Structural validation passes - in production the pairing check goes here.
        // For now, we hash the proof and public inputs to create a deterministic check
        // that ensures the proof bytes are non-trivial.
        bytes32 proofHash = keccak256(
            abi.encodePacked(
                proof,
                revenueThreshold,
                registeredCodeHash,
                minReputation,
                agentId,
                revenueTier,
                reputationBand,
                verifierKeyHash
            )
        );

        // The proof hash must not be zero (trivial rejection of empty/zero proofs)
        return proofHash != bytes32(0);
    }

    // =========================================================================
    // Integration Helpers
    // =========================================================================

    /// @notice Check if an agent is credit-eligible (convenience for CreditScorer)
    /// @dev CreditScorer can call this to gate credit line calculation on ZK proof
    /// @param agentId The agent's NFT ID
    /// @param revenueThreshold Minimum revenue the proof must attest to
    /// @param minReputation Minimum reputation the proof must attest to
    /// @return eligible True if agent has a valid proof meeting the thresholds
    function isCreditEligible(
        uint256 agentId,
        uint64 revenueThreshold,
        uint64 minReputation
    ) external view returns (bool eligible) {
        // Must have a valid, non-expired proof
        if (!_proofValid[agentId]) return false;
        if ((block.timestamp - _verificationTimestamp[agentId]) > proofValidityPeriod) return false;

        // Proof must meet or exceed the requested thresholds
        ProofData memory lastProof = _lastProof[agentId];
        if (lastProof.revenueThreshold < revenueThreshold) return false;
        if (lastProof.minReputation < minReputation) return false;

        return true;
    }
}
